name: "Build"

on: 
  push: 
    paths-ignore: 
      - 'docs/**'
      - '*.md'
    branches: 
      - main

jobs: 
  check: 
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: build --full-stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with: 
          name: error-report
          path: build-reports.zip